### ISSUE TITLE
No Gitflow applied

### ISSUE THREAD

**Issue by longnd** [kokomyoheinhtet/kookle#2]
## Issue
While it was stated clearly in the code challenge requirement that each change should be merged by a pull request
> Use Git during the development process. Push to a public repository on Github or Gitlab.  Make regular commits and merge code using pull requests.

But as far as I can see, you committed code directly into the `master` branch. While you worked alone on this repository, using pull requests to merge code showcases how you can plan the work by splitting the requirements into smaller pieces of changes.

**Comment by kokomyoheinhtet** [comment]
I understand that the task mentioned that I should apply git flow. While I have experience on both gitflow and single branch workflow in my previous development, I believe I understand them pretty well. However, I apologize that I didn't apply in this project because I was really tight in timeline and all the commits are done by keyboard shortcuts. So, I can save time in pushing to repo and more time on development.

**Comment by longnd** [comment]
While I believe omitting git flow would not help much with saving time, I understand the reason. Thank you for the insight.
